repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: 996abf60411a8d954288ac9856aae7602b80cbda  # v0.22.1
    hooks:
      - id: markdownlint-cli2

  - repo: https://github.com/djlint/djLint
    rev: 9112cb64851c95a7802358af285d21ad8b7f6437  # v1.36.4
    hooks:
      - id: djlint-golang
        types_or: [html]
        files: \.html$

  - repo: https://github.com/mrtazz/checkmake
    rev: 59931d556f8f5cf4fbacf2c8390a8122ef7a881d  # v0.3.2
    hooks:
      - id: checkmake
